### ISSUE TITLE
The theory behind vector<size_t> Frame::GetFeaturesInArea(const float &x, const float  &y, const float  &r, const int minLevel, const int maxLevel) const

### ISSUE THREAD

**Issue by Mechazo11** [AlejandroSilvestri/ORB_SLAM2#5]
Dear @AlejandroSilvestri 

Sir, an important part in reducing 3D point candidates in ORBmatcher::SearchByProjection() methods is to compute nearest keypoints corresponding to the 2D projection of each 3D Map Points before optimization.

My questions are the follows
1. Are the undistorted keypoints arranged in a KD-tree?
2. Is Frame::GetFeaturesinArea performing the same operation as https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query_ball_point.html#scipy.spatial.cKDTree.query_ball_point?
3. Where can I look up the theory behind the Frame::GetFeaturesinArea() method? I tried a lot looking for its theory online but so far could not find anything concrete.

With thanks,
@Mechazo11

**Comment by AlejandroSilvestri** [comment]
@Mechazo11 

Hi there.

1- No, they are not.  Keypoints are distributed in grid cells, that is the only (I don't remember another) keypoints spatial classification.  ORB-SLAM2 doesn't use KD-Tree.
2- `Frame::GetFeaturesInArea` is simple.  You provide a square area, the method expands it to whole cells, and return those cell's keypoints within the square.
3- There is no much theory for it.  The goal is to filter and return the keypoints within the square.

There are four `ORBmatcher::SearchByProjection()` methods.  In general, they seek to match keypoints with mappoints projections **by descriptor**.  That's why you don't look for the nearest neighbor.  Any keypoint in the square area is valid, the main validation being descriptor distance.

**Comment by Mechazo11** [comment]
@AlejandroSilvestri  for bullet point 2, is the idea as follows?

We divide the entire image into a N x M grid. Then in each grid, we run a small square window and pick out the key points which fall in the square? Should the square's center be the 2D coordinates of the Map Point?

**Comment by AlejandroSilvestri** [comment]
@Mechazo11 

The grid is made in frame construction.  When you call `GetFeaturesInArea()`, all keypoints are already classified in the grid, covering all the image.  Using the grid avoids wandering through all keypoints to find those belonging to the square.

**Comment by Mechazo11** [comment]
@AlejandroSilvestri Thank you very much for your prompt reply. One last query, so given the fact that all keypoints are assigned to a grid cell (48 x 64) if I recall correctly, how is the rectangular filter moved through the grid? Is it's coordinate the projected 2D coordinate of a Map Point candidate for which we are trying to find the closest 2D keypoints?

**Comment by AlejandroSilvestri** [comment]
@Mechazo11 

That's the idea.
Then you pick the keypoint with the best suited descriptor to the candidate mappoint.

**Comment by Mechazo11** [comment]
@AlejandroSilvestri Thank you very much for taking the time to explain the nuances of GetFeaturesInArea(). I am closing the issue for now but if I do have any follow up questions, I will write back here
